# This code is generated by PyUIbuilder: https://pyuibuilder.com

import tkinter as tk
from tktimepicker import AnalogPicker, AnalogThemes, constants

main = tk.Tk()
main.config(bg="#E4E2E2")
main.title("Main Window")
main.geometry("773x462")

timepicker = AnalogPicker(parent=main, type=constants.HOURS12)
timepicker.configAnalog(canvas_bg="#E4E2E2", textcolor="#000", bg="#EEEEEE", handcolor="#000000", headcolor="#000000")
timepicker.configSpin(bg="#000")
timepicker.place(x=246, y=30, width=250, height=350)


main.mainloop()